(package-refresh-contents)
(package-install 'quelpa)
(package-install 'yasnippet)
(package-install 'company)
(package-install 'dracula-theme)
(package-install 'auctex)
(package-install 'company-auctex)
(package-install 'cdlatex)
(package-install 'anaconda-mode)
(package-install 'company-anaconda)
(package-install 'py-autopep8)
(package-install 'origami)
(package-install 'julia-mode)
(package-install 'julia-repl)
(package-install 'term+)
(package-install 'lsp-mode)
(package-install 'company-lsp)
(quelpa '(lsp-julia :fetcher github :repo "non-Jedi/lsp-julia"))
