;; python
;; (add-hook 'python-mode-hook 'ycw:setup-elpy)
(add-hook 'python-mode-hook 'ycw:setup-anaconda-mode)
;; (add-hook 'python-mode-hook 'ycw:setup-python-basic)

(defun ycw:setup-elpy ()
  (when (boundp 'ycw:python-dir)
    (setq python-shell-interpreter (concat ycw:python-dir "/python"))
    (setq elpy-rpc-pythonpath ycw:python-dir)
    (setq elpy-rpc-python-command (concat ycw:python-dir "/python")))
  (elpy-enable)
  (require 'py-autopep8)
  (py-autopep8-enable-on-save)
  (ycw:company-yas-init)
  (when (require 'flycheck nil t)
    (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
    (add-hook 'elpy-mode-hook 'flycheck-mode))
  )

(defun ycw:setup-anaconda-mode ()
  ;; (add-to-list 'python-shell-extra-pythonpaths python-dir)
  (when (boundp 'ycw:python-dir)
    (setq python-shell-interpreter (concat ycw:python-dir "/python")))
  (anaconda-mode)
  (require 'rx)
  (ycw:company-yas-init 'company-anaconda)
  ;; (setq company-minimum-prefix-length 1)
  )

(defun ycw:setup-python-basic ()
  (when (boundp 'ycw:python-dir)
    (setq python-shell-interpreter (concat ycw:python-dir "/python")))
  (ycw:company-yas-init)
  (add-to-list 'company-backends 'company-jedi)
  )
